name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Auth0 Access Token
        id: get_token
        run: |
          TOKEN=$(curl --request POST \
            --url "https://${{ secrets.AUTH0_DOMAIN }}/oauth/token" \
            --header 'content-type: application/json' \
            --data '{
              "client_id": "${{ secrets.AUTH0_CLIENT_ID }}",
              "client_secret": "${{ secrets.AUTH0_CLIENT_SECRET }}",
              "audience": "${{ secrets.DEPLOY_API_AUDIENCE }}",
              "grant_type": "client_credentials"
            }' | jq -r .access_token)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Trigger Deploy Endpoint
        run: |
          curl -X POST "https://gavinwoods.com/deploy" \
            -H "Authorization: Bearer $TOKEN"

