name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519

          eval $(ssh-agent -s)
          ssh-add /home/runner/.ssh/id_ed25519 <<< "${{ secrets.SSH_PASSPHRASE }}"

          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts

          # Debug: Print SSH_HOST value
          echo "Attempting to connect to: $SSH_HOST"
          ping -c 4 $SSH_HOST  # Test connectivity with 4 pings

          # Attempt SSH connection
          ssh -o StrictHostKeyChecking=no ${USER}@$SSH_HOST "/home/${USER}/scripts/deploy.sh"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock
          SSH_HOST: "${{ secrets.SSH_HOST }}"
          USER: "${{ secrets.USER }}"

