name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519

          eval $(ssh-agent -s)
          ssh-add /home/runner/.ssh/id_ed25519 <<< "${{ secrets.SSH_PASSPHRASE }}"

          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_ed25519 ${USER}@$SSH_HOST "/home/${USER}/scripts/deploy.sh"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock
          SSH_HOST: "${{ secrets.SSH_HOST }}"
          USER: "${{ secrets.USER }}"

