name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run Deploy Script
        run: |
          /home/math/scripts/deploy.sh